# Generated by Django 4.1 on 2022-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_complet', models.CharField(max_length=30)),
                ('Fonction', models.CharField(max_length=25)),
                ('Expertise', models.CharField(max_length=30)),
                ('Profil', models.ImageField(upload_to=True)),
            ],
        ),
    ]
