# Generated by Django 4.1 on 2022-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlp', '0002_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='Expertise',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Fonction',
            field=models.CharField(max_length=50),
        ),
    ]
