# Generated by Django 4.1 on 2022-09-28 18:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlp', '0003_alter_equipe_expertise_alter_equipe_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='Profil',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
