# Generated by Django 4.1 on 2022-09-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlp', '0005_alter_equipe_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
