# Generated by Django 4.1 on 2022-09-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlp', '0007_equipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
