# Generated by Django 4.1 on 2022-09-30 21:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlp', '0008_delete_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_complet', models.CharField(max_length=30)),
                ('Fonction', models.CharField(max_length=50)),
                ('Expertise', models.CharField(max_length=50)),
                ('Profil', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\PythonDev\\Projects\\first_app\\media'), upload_to='')),
                ('Adresse_mail', models.CharField(max_length=30)),
                ('Lien_fcbk', models.CharField(max_length=50)),
                ('Lien_insta', models.CharField(max_length=50)),
                ('Lien_tweet', models.CharField(max_length=50)),
                ('Lien_whatsapp', models.CharField(max_length=50)),
                ('Lien_linkedin', models.CharField(max_length=50)),
            ],
        ),
    ]
