# Generated by Django 4.1 on 2022-09-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlp', '0009_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='Adresse_mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Lien_fcbk',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Lien_insta',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Lien_linkedin',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Lien_tweet',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Lien_whatsapp',
            field=models.CharField(max_length=70),
        ),
    ]
