# Generated by Django 4.1 on 2022-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlp', '0010_alter_equipe_adresse_mail_alter_equipe_lien_fcbk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_complet', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('objet', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=450)),
            ],
        ),
    ]
